import theme from './styles/theme';

const Data = [
  {
    key: 'A',
    value: 50,
    quantity: 1,
    selected: false,
    color: theme.colors.tiles[0],
  },
  {
    key: 'B',
    value: 40,
    quantity: 1,
    selected: false,
    color: theme.colors.tiles[1],
  },
  {
    key: 'C',
    value: 30,
    quantity: 1,
    selected: false,
    color: theme.colors.tiles[2],
  },
  {
    key: 'D',
    value: 20,
    quantity: 1,
    selected: false,
    color: theme.colors.tiles[3],
  },
  {
    key: 'E',
    value: 10,
    quantity: 1,
    selected: false,
    color: theme.colors.tiles[4],
  },
  {
    key: 'F',
    value: 5,
    quantity: 1,
    selected: false,
    color: theme.colors.tiles[5],
  },
  {
    key: 'G',
    value: 50,
    quantity: 1,
    selected: false,
    color: theme.colors.tiles[0],
  },
  {
    key: 'H',
    value: 40,
    quantity: 1,
    selected: false,
    color: theme.colors.tiles[1],
  },
  {
    key: 'I',
    value: 30,
    quantity: 1,
    selected: false,
    color: theme.colors.tiles[2],
  },
  {
    key: 'J',
    value: 20,
    quantity: 1,
    selected: false,
    color: theme.colors.tiles[3],
  },
  {
    key: 'K',
    value: 10,
    quantity: 1,
    selected: false,
    color: theme.colors.tiles[4],
  },
  {
    key: 'L',
    value: 5,
    quantity: 1,
    selected: false,
    color: theme.colors.tiles[5],
  },
  {
    key: 'M',
    value: 50,
    quantity: 1,
    selected: false,
    color: theme.colors.tiles[0],
  },
  {
    key: 'N',
    value: 40,
    quantity: 1,
    selected: false,
    color: theme.colors.tiles[1],
  },
  {
    key: 'O',
    value: 30,
    quantity: 1,
    selected: false,
    color: theme.colors.tiles[2],
  },
  {
    key: 'P',
    value: 20,
    quantity: 1,
    selected: false,
    color: theme.colors.tiles[3],
  },
  {
    key: 'Q',
    value: 10,
    quantity: 1,
    selected: false,
    color: theme.colors.tiles[4],
  },
  {
    key: 'R',
    value: 5,
    quantity: 1,
    selected: false,
    color: theme.colors.tiles[5],
  },
  {
    key: 'S',
    value: 50,
    quantity: 1,
    selected: false,
    color: theme.colors.tiles[0],
  },
  {
    key: 'T',
    value: 40,
    quantity: 1,
    selected: false,
    color: theme.colors.tiles[1],
  },
  {
    key: 'U',
    value: 30,
    quantity: 1,
    selected: false,
    color: theme.colors.tiles[2],
  },
  {
    key: 'V',
    value: 20,
    quantity: 1,
    selected: false,
    color: theme.colors.tiles[3],
  },
  {
    key: 'W',
    value: 10,
    quantity: 1,
    selected: false,
    color: theme.colors.tiles[4],
  },
  {
    key: 'X',
    value: 5,
    quantity: 1,
    selected: false,
    color: theme.colors.tiles[5],
  },
  {
    key: 'Y',
    value: 10,
    quantity: 1,
    selected: false,
    color: theme.colors.tiles[4],
  },
  {
    key: 'Z',
    value: 5,
    quantity: 1,
    selected: false,
    color: theme.colors.tiles[5],
  },
];

const API = {
  bonusKey: ['X', 'B', 'A'],
  data: Data,
};

export default API;
